version: "3"
services:
  node:
    container_name: node
    image: node
    stdin_open: true # docker run -i
    tty: true # docker run -t
    # command: tail -f yarn.lock
    working_dir: /code
    ports:
      - 3000:3000
    volumes:
      - .:/code
      - /code/node_modules
