version: "3"
services:
  node:
    container_name: node
    image: node
    stdin_open: true
    tty: true
    working_dir: /code
    ports:
      - 3000:3000
    volumes:
      - .:/code
      - node_modules:/code/node_modules
volumes:
  node_modules:
