version: '3'
services:
  deno:
    container_name: deno
    image: denoland/deno:latest
    restart: unless-stopped
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    working_dir: /code
    command: [ "/bin/sh", "-c", "trap : TERM INT; while :; do echo Ready to code like a rockstar!!!; sleep 2073600; done & wait" ]
    ports:
      - 3000:3000
    volumes:
      - deno:/deno-dir
      - .:/code
    depends_on:
      - couchdb
      - postgres
      - redis
      - rabbitmq
    
  couchdb:
    container_name: couchdb
    image: couchdb
    restart: always
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb:/opt/couchdb/data 

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql/data 

  redis:
    container_name: redis
    image: redis
    restart: always
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq
    restart: always

volumes:
  deno:
  couchdb:
  postgres:
  