version: '3'
services:
    stdin_open: true # docker run -i
  node:
    container_name: node
    image: node
    tty: true        # docker run -t
    # command: tail -f yarn.lock
    working_dir: /code
    ports:
      - 3000:3000
    volumes:
      - .:/code
      - /code/node_modules
    depends_on:
      - mongo
      - mariadb
      - memcached
    
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    # you need to configure a crypto key when creating a replica set.
    volumes:
      - mongo:/data/db
  
  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - mariadb:/var/lib/mysql
  
  memcached:
    container_name: memcached
    image: memcached
    restart: always

  
volumes:
  mongo:
  mariadb:
  
