check name:
  npm run check src/{{name}}.ts

build name:
  npm run build src/{{name}}.ts

run name:
  npm run exec src/{{name}}.ts

test name='*':
  npm run test src/{{name}}.test.ts

clean:
  rm src/*.js
