/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseStateRouteImport } from './routes/use-state'
import { Route as UseRefRouteImport } from './routes/use-ref'
import { Route as UseReducerRouteImport } from './routes/use-reducer'
import { Route as UseMemoRouteImport } from './routes/use-memo'
import { Route as UseEffectRouteImport } from './routes/use-effect'
import { Route as UseContextRouteImport } from './routes/use-context'
import { Route as UseCallbackRouteImport } from './routes/use-callback'
import { Route as SuspenseRouteImport } from './routes/suspense'
import { Route as CustomHooksRouteImport } from './routes/custom-hooks'
import { Route as IndexRouteImport } from './routes/index'

const UseStateRoute = UseStateRouteImport.update({
  id: '/use-state',
  path: '/use-state',
  getParentRoute: () => rootRouteImport,
} as any)
const UseRefRoute = UseRefRouteImport.update({
  id: '/use-ref',
  path: '/use-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const UseReducerRoute = UseReducerRouteImport.update({
  id: '/use-reducer',
  path: '/use-reducer',
  getParentRoute: () => rootRouteImport,
} as any)
const UseMemoRoute = UseMemoRouteImport.update({
  id: '/use-memo',
  path: '/use-memo',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectRoute = UseEffectRouteImport.update({
  id: '/use-effect',
  path: '/use-effect',
  getParentRoute: () => rootRouteImport,
} as any)
const UseContextRoute = UseContextRouteImport.update({
  id: '/use-context',
  path: '/use-context',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCallbackRoute = UseCallbackRouteImport.update({
  id: '/use-callback',
  path: '/use-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspenseRoute = SuspenseRouteImport.update({
  id: '/suspense',
  path: '/suspense',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomHooksRoute = CustomHooksRouteImport.update({
  id: '/custom-hooks',
  path: '/custom-hooks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/custom-hooks': typeof CustomHooksRoute
  '/suspense': typeof SuspenseRoute
  '/use-callback': typeof UseCallbackRoute
  '/use-context': typeof UseContextRoute
  '/use-effect': typeof UseEffectRoute
  '/use-memo': typeof UseMemoRoute
  '/use-reducer': typeof UseReducerRoute
  '/use-ref': typeof UseRefRoute
  '/use-state': typeof UseStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/custom-hooks': typeof CustomHooksRoute
  '/suspense': typeof SuspenseRoute
  '/use-callback': typeof UseCallbackRoute
  '/use-context': typeof UseContextRoute
  '/use-effect': typeof UseEffectRoute
  '/use-memo': typeof UseMemoRoute
  '/use-reducer': typeof UseReducerRoute
  '/use-ref': typeof UseRefRoute
  '/use-state': typeof UseStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/custom-hooks': typeof CustomHooksRoute
  '/suspense': typeof SuspenseRoute
  '/use-callback': typeof UseCallbackRoute
  '/use-context': typeof UseContextRoute
  '/use-effect': typeof UseEffectRoute
  '/use-memo': typeof UseMemoRoute
  '/use-reducer': typeof UseReducerRoute
  '/use-ref': typeof UseRefRoute
  '/use-state': typeof UseStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/custom-hooks'
    | '/suspense'
    | '/use-callback'
    | '/use-context'
    | '/use-effect'
    | '/use-memo'
    | '/use-reducer'
    | '/use-ref'
    | '/use-state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/custom-hooks'
    | '/suspense'
    | '/use-callback'
    | '/use-context'
    | '/use-effect'
    | '/use-memo'
    | '/use-reducer'
    | '/use-ref'
    | '/use-state'
  id:
    | '__root__'
    | '/'
    | '/custom-hooks'
    | '/suspense'
    | '/use-callback'
    | '/use-context'
    | '/use-effect'
    | '/use-memo'
    | '/use-reducer'
    | '/use-ref'
    | '/use-state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomHooksRoute: typeof CustomHooksRoute
  SuspenseRoute: typeof SuspenseRoute
  UseCallbackRoute: typeof UseCallbackRoute
  UseContextRoute: typeof UseContextRoute
  UseEffectRoute: typeof UseEffectRoute
  UseMemoRoute: typeof UseMemoRoute
  UseReducerRoute: typeof UseReducerRoute
  UseRefRoute: typeof UseRefRoute
  UseStateRoute: typeof UseStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-state': {
      id: '/use-state'
      path: '/use-state'
      fullPath: '/use-state'
      preLoaderRoute: typeof UseStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-ref': {
      id: '/use-ref'
      path: '/use-ref'
      fullPath: '/use-ref'
      preLoaderRoute: typeof UseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-reducer': {
      id: '/use-reducer'
      path: '/use-reducer'
      fullPath: '/use-reducer'
      preLoaderRoute: typeof UseReducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-memo': {
      id: '/use-memo'
      path: '/use-memo'
      fullPath: '/use-memo'
      preLoaderRoute: typeof UseMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-effect': {
      id: '/use-effect'
      path: '/use-effect'
      fullPath: '/use-effect'
      preLoaderRoute: typeof UseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-context': {
      id: '/use-context'
      path: '/use-context'
      fullPath: '/use-context'
      preLoaderRoute: typeof UseContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-callback': {
      id: '/use-callback'
      path: '/use-callback'
      fullPath: '/use-callback'
      preLoaderRoute: typeof UseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspense': {
      id: '/suspense'
      path: '/suspense'
      fullPath: '/suspense'
      preLoaderRoute: typeof SuspenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-hooks': {
      id: '/custom-hooks'
      path: '/custom-hooks'
      fullPath: '/custom-hooks'
      preLoaderRoute: typeof CustomHooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomHooksRoute: CustomHooksRoute,
  SuspenseRoute: SuspenseRoute,
  UseCallbackRoute: UseCallbackRoute,
  UseContextRoute: UseContextRoute,
  UseEffectRoute: UseEffectRoute,
  UseMemoRoute: UseMemoRoute,
  UseReducerRoute: UseReducerRoute,
  UseRefRoute: UseRefRoute,
  UseStateRoute: UseStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
