// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var newScore = 20;

var message = "hello world";

console.log("Enjoying the docs so far?");

function calculate(x) {
  return x + 1 | 0;
}

var result = 1;

var result$1 = result + 1 | 0;

console.log(result$1);

var greeting = "hello!";

var score = 10;

var displayGreeting = true;

exports.greeting = greeting;
exports.score = score;
exports.newScore = newScore;
exports.message = message;
exports.displayGreeting = displayGreeting;
exports.calculate = calculate;
exports.result = result$1;
/*  Not a pure module */
