// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, ReScript/ReasonML");

console.log(5);

var y = {
  contents: 5
};

y.contents = y.contents + 11 | 0;

console.log(y.contents);

var c = "hello world";

console.log(c);

var message = "message";

var s = "hello " + message + " interpolate";

console.log(s);

var myPoint = {
  x: 11,
  y: 12
};

myPoint.y = 30;

console.log(myPoint);

function name(arg) {
  return arg;
}

var resName = "Diego Vila";

console.log(resName);

function myFun(x, y) {
  var doubleX = x + x | 0;
  var doubleY = y + y | 0;
  return doubleX + doubleY | 0;
}

console.log("this returns int: " + String(myFun(2, 2)));

var fl = 9.1 + 5;

console.log(fl);

var mulf = 34 * 10.33;

console.log(mulf);

function getInt(a) {
  return a + 8 | 0;
}

console.log("this returns an int " + String(16));

var x = 5;

var resGetInt = 16;

exports.x = x;
exports.y = y;
exports.c = c;
exports.message = message;
exports.s = s;
exports.myPoint = myPoint;
exports.name = name;
exports.resName = resName;
exports.myFun = myFun;
exports.fl = fl;
exports.mulf = mulf;
exports.getInt = getInt;
exports.resGetInt = resGetInt;
/*  Not a pure module */
