// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var newScore = 20;

var message = "hello world";

console.log(message);

console.log("Enjoying the docs so far?");

function calculate(x) {
  return x + 1 | 0;
}

function calculateSomeMore(x) {
  return x + 2 | 0;
}

var result2 = 1;

var result3 = result2 + 2 | 0;

function add(a, b) {
  return a + b | 0;
}

function add$prime(x, y) {
  return x + y | 0;
}

console.log(33);

console.log(10);

console.log([
      10,
      20,
      20
    ]);

console.log([
      1.1,
      2.2,
      2.2
    ]);

var payloadResults = [
  {
    TAG: /* Ok */0,
    _0: {
      data: "hi"
    }
  },
  {
    TAG: /* Ok */0,
    _0: {
      data: "bye"
    }
  },
  {
    TAG: /* Error */1,
    _0: "Something wrong happened!"
  }
];

console.log(30.5);

var meNextYear = {
  age: 6,
  name: "Big ReScript"
};

var baby = {
  name: "Baby ReScript",
  age: 5
};

baby.age = baby.age + 1 | 0;

var meo = {
  age: 5,
  name: "Big ReScript"
};

var age = meo.age;

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

var message$1 = myList ? "test" + (1).toString() : "foo";

function addCoordinates(x, y) {
  return x + y | 0;
}

function drawCircle(color, radius, param) {
  console.log(color);
  if (radius !== undefined) {
    console.log(radius.toString());
  } else {
    console.log("nono");
  }
  
}

var greeting = "hello!";

var displayGreeting = true;

var result1 = 0;

var score = 10;

var resr = 33;

var a = [
  10,
  20,
  20
];

var b = [
  1.1,
  2.2,
  2.2
];

var my3dCoordinates = [
  20.0,
  30.5,
  100.0
];

var name = "Big ReScript";

var areYouCrushingIt = /* Yes */0;

var myAccount = {
  TAG: /* Facebook */1,
  _0: "Josh",
  _1: 26
};

var friendAccount = {
  TAG: /* Instagram */0,
  _0: "Jenny"
};

var me = {
  TAG: /* Id */1,
  name: "Joe",
  password: "123"
};

var x = 5;

var y;

var res = 8;

exports.greeting = greeting;
exports.newScore = newScore;
exports.displayGreeting = displayGreeting;
exports.calculate = calculate;
exports.calculateSomeMore = calculateSomeMore;
exports.result1 = result1;
exports.result2 = result2;
exports.result3 = result3;
exports.add = add;
exports.score = score;
exports.add$prime = add$prime;
exports.resr = resr;
exports.a = a;
exports.b = b;
exports.payloadResults = payloadResults;
exports.my3dCoordinates = my3dCoordinates;
exports.name = name;
exports.meNextYear = meNextYear;
exports.baby = baby;
exports.meo = meo;
exports.age = age;
exports.areYouCrushingIt = areYouCrushingIt;
exports.myAccount = myAccount;
exports.friendAccount = friendAccount;
exports.me = me;
exports.x = x;
exports.y = y;
exports.myList = myList;
exports.message = message$1;
exports.addCoordinates = addCoordinates;
exports.res = res;
exports.drawCircle = drawCircle;
/*  Not a pure module */
