// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log(10);

console.log(8);

var myInt = 10;

var myInt$1 = 9 + myInt | 0;

function add(x, y) {
  return x + y | 0;
}

console.log(4);

function drawCircle(r) {
  return r + 55 | 0;
}

console.log(59);

console.log(109);

var score = 10;

var score$prime = 11;

var x = 109;

exports.score = score;
exports.score$prime = score$prime;
exports.myInt = myInt$1;
exports.add = add;
exports.drawCircle = drawCircle;
exports.x = x;
/*  Not a pure module */
