/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UseStateRouteImport } from './routes/use-state'
import { Route as UseRefRouteImport } from './routes/use-ref'
import { Route as UseReducerRouteImport } from './routes/use-reducer'
import { Route as UseMemoRouteImport } from './routes/use-memo'
import { Route as UseEffectRouteImport } from './routes/use-effect'
import { Route as UseContextRouteImport } from './routes/use-context'
import { Route as UseCallbackRouteImport } from './routes/use-callback'
import { Route as SignalsRouteImport } from './routes/signals'
import { Route as PortalsRouteImport } from './routes/portals'
import { Route as MemoRouteImport } from './routes/memo'
import { Route as ForwardRefRouteImport } from './routes/forward-ref'
import { Route as ErrorBoundaryRouteImport } from './routes/error-boundary'
import { Route as IndexRouteImport } from './routes/index'

const UseStateRoute = UseStateRouteImport.update({
  id: '/use-state',
  path: '/use-state',
  getParentRoute: () => rootRouteImport,
} as any)
const UseRefRoute = UseRefRouteImport.update({
  id: '/use-ref',
  path: '/use-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const UseReducerRoute = UseReducerRouteImport.update({
  id: '/use-reducer',
  path: '/use-reducer',
  getParentRoute: () => rootRouteImport,
} as any)
const UseMemoRoute = UseMemoRouteImport.update({
  id: '/use-memo',
  path: '/use-memo',
  getParentRoute: () => rootRouteImport,
} as any)
const UseEffectRoute = UseEffectRouteImport.update({
  id: '/use-effect',
  path: '/use-effect',
  getParentRoute: () => rootRouteImport,
} as any)
const UseContextRoute = UseContextRouteImport.update({
  id: '/use-context',
  path: '/use-context',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCallbackRoute = UseCallbackRouteImport.update({
  id: '/use-callback',
  path: '/use-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalsRoute = SignalsRouteImport.update({
  id: '/signals',
  path: '/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalsRoute = PortalsRouteImport.update({
  id: '/portals',
  path: '/portals',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoRoute = MemoRouteImport.update({
  id: '/memo',
  path: '/memo',
  getParentRoute: () => rootRouteImport,
} as any)
const ForwardRefRoute = ForwardRefRouteImport.update({
  id: '/forward-ref',
  path: '/forward-ref',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorBoundaryRoute = ErrorBoundaryRouteImport.update({
  id: '/error-boundary',
  path: '/error-boundary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/error-boundary': typeof ErrorBoundaryRoute
  '/forward-ref': typeof ForwardRefRoute
  '/memo': typeof MemoRoute
  '/portals': typeof PortalsRoute
  '/signals': typeof SignalsRoute
  '/use-callback': typeof UseCallbackRoute
  '/use-context': typeof UseContextRoute
  '/use-effect': typeof UseEffectRoute
  '/use-memo': typeof UseMemoRoute
  '/use-reducer': typeof UseReducerRoute
  '/use-ref': typeof UseRefRoute
  '/use-state': typeof UseStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/error-boundary': typeof ErrorBoundaryRoute
  '/forward-ref': typeof ForwardRefRoute
  '/memo': typeof MemoRoute
  '/portals': typeof PortalsRoute
  '/signals': typeof SignalsRoute
  '/use-callback': typeof UseCallbackRoute
  '/use-context': typeof UseContextRoute
  '/use-effect': typeof UseEffectRoute
  '/use-memo': typeof UseMemoRoute
  '/use-reducer': typeof UseReducerRoute
  '/use-ref': typeof UseRefRoute
  '/use-state': typeof UseStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/error-boundary': typeof ErrorBoundaryRoute
  '/forward-ref': typeof ForwardRefRoute
  '/memo': typeof MemoRoute
  '/portals': typeof PortalsRoute
  '/signals': typeof SignalsRoute
  '/use-callback': typeof UseCallbackRoute
  '/use-context': typeof UseContextRoute
  '/use-effect': typeof UseEffectRoute
  '/use-memo': typeof UseMemoRoute
  '/use-reducer': typeof UseReducerRoute
  '/use-ref': typeof UseRefRoute
  '/use-state': typeof UseStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error-boundary'
    | '/forward-ref'
    | '/memo'
    | '/portals'
    | '/signals'
    | '/use-callback'
    | '/use-context'
    | '/use-effect'
    | '/use-memo'
    | '/use-reducer'
    | '/use-ref'
    | '/use-state'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/error-boundary'
    | '/forward-ref'
    | '/memo'
    | '/portals'
    | '/signals'
    | '/use-callback'
    | '/use-context'
    | '/use-effect'
    | '/use-memo'
    | '/use-reducer'
    | '/use-ref'
    | '/use-state'
  id:
    | '__root__'
    | '/'
    | '/error-boundary'
    | '/forward-ref'
    | '/memo'
    | '/portals'
    | '/signals'
    | '/use-callback'
    | '/use-context'
    | '/use-effect'
    | '/use-memo'
    | '/use-reducer'
    | '/use-ref'
    | '/use-state'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ErrorBoundaryRoute: typeof ErrorBoundaryRoute
  ForwardRefRoute: typeof ForwardRefRoute
  MemoRoute: typeof MemoRoute
  PortalsRoute: typeof PortalsRoute
  SignalsRoute: typeof SignalsRoute
  UseCallbackRoute: typeof UseCallbackRoute
  UseContextRoute: typeof UseContextRoute
  UseEffectRoute: typeof UseEffectRoute
  UseMemoRoute: typeof UseMemoRoute
  UseReducerRoute: typeof UseReducerRoute
  UseRefRoute: typeof UseRefRoute
  UseStateRoute: typeof UseStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/use-state': {
      id: '/use-state'
      path: '/use-state'
      fullPath: '/use-state'
      preLoaderRoute: typeof UseStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-ref': {
      id: '/use-ref'
      path: '/use-ref'
      fullPath: '/use-ref'
      preLoaderRoute: typeof UseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-reducer': {
      id: '/use-reducer'
      path: '/use-reducer'
      fullPath: '/use-reducer'
      preLoaderRoute: typeof UseReducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-memo': {
      id: '/use-memo'
      path: '/use-memo'
      fullPath: '/use-memo'
      preLoaderRoute: typeof UseMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-effect': {
      id: '/use-effect'
      path: '/use-effect'
      fullPath: '/use-effect'
      preLoaderRoute: typeof UseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-context': {
      id: '/use-context'
      path: '/use-context'
      fullPath: '/use-context'
      preLoaderRoute: typeof UseContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-callback': {
      id: '/use-callback'
      path: '/use-callback'
      fullPath: '/use-callback'
      preLoaderRoute: typeof UseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signals': {
      id: '/signals'
      path: '/signals'
      fullPath: '/signals'
      preLoaderRoute: typeof SignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portals': {
      id: '/portals'
      path: '/portals'
      fullPath: '/portals'
      preLoaderRoute: typeof PortalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memo': {
      id: '/memo'
      path: '/memo'
      fullPath: '/memo'
      preLoaderRoute: typeof MemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forward-ref': {
      id: '/forward-ref'
      path: '/forward-ref'
      fullPath: '/forward-ref'
      preLoaderRoute: typeof ForwardRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error-boundary': {
      id: '/error-boundary'
      path: '/error-boundary'
      fullPath: '/error-boundary'
      preLoaderRoute: typeof ErrorBoundaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ErrorBoundaryRoute: ErrorBoundaryRoute,
  ForwardRefRoute: ForwardRefRoute,
  MemoRoute: MemoRoute,
  PortalsRoute: PortalsRoute,
  SignalsRoute: SignalsRoute,
  UseCallbackRoute: UseCallbackRoute,
  UseContextRoute: UseContextRoute,
  UseEffectRoute: UseEffectRoute,
  UseMemoRoute: UseMemoRoute,
  UseReducerRoute: UseReducerRoute,
  UseRefRoute: UseRefRoute,
  UseStateRoute: UseStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
