// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


console.log("Hello, ReScript");

var y = {
  contents: 5
};

y.contents = y.contents + 1 | 0;

var message = "message";

var s = "hello " + message;

function name(arg) {
  return arg;
}

function myFun(x, y) {
  var doubleX = x + x | 0;
  var doubleY = y + y | 0;
  return doubleX + doubleY | 0;
}

var x = 5;

var c = "hello world";

exports.x = x;
exports.y = y;
exports.c = c;
exports.message = message;
exports.s = s;
exports.name = name;
exports.myFun = myFun;
/*  Not a pure module */
