// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function make(param) {
  return React.createElement("div", undefined, "Hello World");
}

exports.make = make;
/* react Not a pure module */
